# Generated by Django 4.1.1 on 2022-09-11 13:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vcf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('CHROM', models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator('^chr(?:[1-9]|[1][0-9]|[[2][0-2]|[XYM])$', 'only valid email is required')])),
                ('POS', models.IntegerField(blank=True, null=True)),
                ('ID_seq', models.CharField(blank=True, max_length=100, verbose_name='ID')),
                ('ALT', models.CharField(blank=True, choices=[('A', 'A'), ('G', 'G'), ('C', 'C'), ('T', 'T'), ('.', '.')], max_length=100)),
                ('REF', models.CharField(blank=True, choices=[('A', 'A'), ('G', 'G'), ('C', 'C'), ('T', 'T'), ('.', '.')], max_length=100)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
